/**
 * Códigos de error estandarizados para toda la aplicación
 */
export enum ErrorCode {
  // Errores de sistema
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  
  // Errores de validación
  INVALID_INPUT = 'INVALID_INPUT',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  
  // Errores de autenticación y autorización
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  
  // Errores de recursos
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  
  // Errores de negocio específicos
  CONSENT_EXPIRED = 'CONSENT_EXPIRED',
  CONSENT_ALREADY_PROCESSED = 'CONSENT_ALREADY_PROCESSED',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  COMPANY_CONTEXT_REQUIRED = 'COMPANY_CONTEXT_REQUIRED',
  POLICY_VERSION_CONFLICT = 'POLICY_VERSION_CONFLICT'
} 